project:
  type: website
  output-dir: docs

website:
  title: "Mohammad Rashidul Hashan"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

